
export const EVENT_BOOKINGS_REQUEST = 'app/HomePage/EVENT_BOOKINGS_REQUEST';
export const EVENT_BOOKINGS_SUCCESS = 'app/HomePage/EVENT_BOOKINGS_SUCCESS';
export const EVENT_BOOKINGS_ERROR = 'app/HomePage/EVENT_BOOKINGS_ERROR';

export const CANCEL_BOOKING_REQUEST = 'app/HomePage/CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'app/HomePage/CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_ERROR = 'app/HomePage/CANCEL_BOOKING_ERROR';

export const BOOKINGS_RECEIVED = 'app/HomePage/BOOKINGS_RECEIVED';
