
export const EVENT_BOOKINGS_REQUEST = 'app/HomePage/EVENT_BOOKINGS_REQUEST';
export const EVENT_BOOKINGS_SUCCESS = 'app/HomePage/EVENT_BOOKINGS_SUCCESS';
export const EVENT_BOOKINGS_ERROR = 'app/HomePage/EVENT_BOOKINGS_ERROR';

export const BOOKINGS_RECEIVED = 'app/HomePage/BOOKINGS_RECEIVED';
